name: 'oh_my_stack'
version: '0.0.1'
description: 'a web restful application that'
environment:
    sdk: ">=1.0.0 < 2.0.0"
 
 
dependencies:
    logging: '>=0.11.1 <0.12.0'
    logging_handlers: ">=0.8.0 <0.9.0"
    browser: '>=0.10.0 <0.11.0'
    dart_to_js_script_rewriter: '^0.1.0'
    google_charts: "^0.1.4"
    func: ^0.1.0
    js: ^0.6.0
    rpc: '>=0.5.0 <0.6.0'
 
transformers:
- dart_to_js_script_rewriter